Improve error handling

diff --git a/implant b/implant
--- a/implant
+++ b/implant
@@ -26,6 +26,10 @@ get_link(){
     echo $link
 }
 
+remove_link(){
+    sed "/^$name=/d" -i $WAREHOUSE/index
+}
+
 get_path(){
     cut -d"=" -f2- <<<$(get_link $1)
 }
@@ -43,16 +47,16 @@ pull(){
         then
             local name=$(sed "s#/#_#g" <<<$path)
         fi
-        git clone https://github.com/$path $WAREHOUSE/$name
-        echo $WAREHOUSE/$name
+        git clone https://github.com/$path $WAREHOUSE/$name &&
+            echo $WAREHOUSE/$name
     else
         local name=$(basename $path)
         if [[ -e $WAREHOUSE/$name ]]
         then
             local name=$(sed "s#/#_#g" <<<$path)
         fi
-        git clone $path $WAREHOUSE/$name
-        echo $WAREHOUSE/$name
+        git clone $path $WAREHOUSE/$name &&
+            echo $WAREHOUSE/$name
     fi
 }
 
@@ -110,21 +114,21 @@ install(){
         return 1
     fi
     local path=$(pull $1)
+    [[ -n "$path" ]] ||
+        error "Unable to clone repository."
     install_pkg $path
 }
 
 update(){
     local name=$1
     local path=$(get_path $1)
-    if [[ ! -e "$path" ]]
-    then
+    [[ -e "$path" ]] ||
         error "The package $name is not installed."
-    fi
 
     clean_links "$path"
-    cd $path
-    git pull
-    link_scripts $path
+    cd $path || error "$path does not exist."
+    git pull || error "Cannot pull modifications."
+    link_scripts $path || error "Error while link scripts."
 }
 
 dir(){
@@ -147,20 +151,16 @@ dir(){
 remove(){
     local name=$1
     local path=$(get_path $1)
-    if [[ ! -e "$path" ]]
-    then
+    [[ -e "$path" ]] ||
         error "The package $name is not installed."
-    fi
 
     local pkg=$path/package.json
     echo "Package $name at $path will be removed."
     echo "Continue ? [y/N]"
     local rep
     read rep
-    if [[ ! "$rep" =~ '[Yy]\(es\)*' ]]
-    then
+    [[ "$rep" =~ '[Yy]\(es\)*' ]] ||
         error "Aborted."
-    fi
 
     local i=0
     local script=$(jq .scripts <$pkg | jq -r .[$i])
@@ -172,7 +172,7 @@ remove(){
         local script=$(jq .scripts <$pkg | jq -r .[$i])
     done
     rm -rf $WAREHOUSE/$name
-    sed "/$name/d" -i $WAREHOUSE/index
+    remove_link $name
 }
 
 help(){
